[package]
name = "dose-derive"
version = "0.1.1"
edition = "2021"
description = "Attributes for dose"
license = "GPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
